version: '3.7'
services:
  #######################################################
  # Redis
  #######################################################
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - ./volumes/redis:/data
    deploy:
      restart_policy:
        condition: on-failure

  #######################################################
  # Postgres
  #######################################################
  postgresdb:
    image: postgres:alpine
    ports:
      - '5432:5432'
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rcr_api
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
