services:
  ##############################################################################################################
  # rod_catch_returns rcr_api
  ##############################################################################################################
  rcr_api:
    image: rod_catch_returns/rcr_api:${TAG:-latest}
    ports:
      - 5000:5000
    env_file:
      - ../.env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
