version: '3.8'
#######################################################
# Common project docker build options
#######################################################
x-common-build-options: &common-build-options
  context: ${BUILD_CONTEXT:-../}

services:
  ##############################################################################################################
  # Rod Catch Returns services base image
  #
  # This is not designed to be deployed but to serve as the base image for rod-catch-returns services.
  ##############################################################################################################
  rod_catch_returns_base:
    image: rod_catch_returns/base
    build:
      <<: *common-build-options
      dockerfile: Dockerfile.base

  ##############################################################################################################
  # rod-catch-returns services builder image
  #
  # This is not designed to be deployed but to serve as the base image for building rod-catch-returns services.
  # Provides additional libraries for the build process not required at runtime.
  ##############################################################################################################
  rod_catch_returns_builder:
    image: rod_catch_returns/builder
    build:
      <<: *common-build-options
      dockerfile: Dockerfile.build

  ##############################################################################################################
  # rod-catch-returns rcr_api
  ##############################################################################################################
  rcr_api:
    image: rod_catch_returns/rcr_api:${TAG:-latest}
    build:
      <<: *common-build-options
      dockerfile: ${PROJECT_DOCKERFILE:-Dockerfile}
